### ISSUE TITLE
Kubernetes: debug(Launch) failed with Nodejs project

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#155]
Repro steps:
1. create a project following this doc : https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
2. set proper vsdocker.imageUser in user setting and docker login
3.  execute "Kubernetes: debug(Launch)"  and input debug command "node debug server.js"

expect: the debugger will start
actually: 
![image](https://user-images.githubusercontent.com/4318793/38190100-505248d2-3695-11e8-8ab3-adf84b15ef87.png)

Then we execute "Kubernetes: Remove debug" an error occured. 
![image](https://user-images.githubusercontent.com/4318793/38190178-b31dcad6-3695-11e8-8612-c08855cdd65e.png)

**Comment by lstocchi** [comment]
This should be fixed by #756 and it is now part of the new release 1.2.1. Closing it. 
You can find some more infos [in the documentation](https://github.com/Azure/vscode-kubernetes-tools/blob/27882d74f49c73062b818982eca198bf91d4821f/debug-on-kubernetes.md#7-nodejs-debugging).
If you still face any issues with it let us know and/or feel free to reopen it. Thank you :)
