### ISSUE TITLE
The name of added ACS is different from the real name on portal

### ISSUE THREAD

**Issue by bsaby** [Azure/vscode-kubernetes-tools#178]
Vscode Kubernetes:
![image](https://user-images.githubusercontent.com/22470312/38864076-299deea2-426c-11e8-9463-9d57cc1f213d.png)
Portal:
![image](https://user-images.githubusercontent.com/22470312/38864085-2e1d9234-426c-11e8-816a-9b70a63ffc56.png)

**Comment by itowlson** [comment]
It looks like this is what the Azure CLI does when you do a `az acs kubernetes get-credentials` - the name of the kubeconfig entry is different from the Azure cluster name.  I'll raise this with the Azure CLI folks.

**Comment by itowlson** [comment]
ACS/AKS team say that this is by design.  So this will continue to be the default for the VS Code tree view.

That said, I noticed that the tree view is using the cluster name from kubeconfig, rather than the context name.  We could change this to use the context name, which would give the same behaviour by default, but would all you to rename entries by using `kubectl rename-context` from the command line.

@squillace Does this make sense to you, to align the tree view with kubeconfig context names instead of cluster names?  At the kubeconfig/kubectl level the things we display _are_ contexts rather than clusters...

**Comment by itowlson** [comment]
@gillesdemey Yeah, I think we should display context names instead of cluster names, so that `rename-context` would work.  I'll send a PR and people can thumbs-down it if they disagree...
