### ISSUE TITLE
Kubernetes Debug (Launch) doesn't push NodeJS app to Minikube

### ISSUE THREAD

**Issue by sgpennebaker** [Azure/vscode-kubernetes-tools#183]
Trying to push a simple express "hello world" to a simple minikube. ` Kubernetes Run` works fine, `Kubernetes Debug (Launch)` / `node` does the Docker push steps but doesn't launch the app.  Could be documentation, [Debug support on Kubernetes cluster](https://github.com/Azure/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md) doesn't cover Node.

**Comment by testforstephen** [comment]
@itowlson Currently only Java has used the new debug framework i designed, Node.js still used the legacy code to launch local debugging.

**Comment by squillace** [comment]
@radu-matei you see this one?

**Comment by squillace** [comment]
It might be related to #192

**Comment by radu-matei** [comment]
This uses the debug features without Draft, so it's not related to #192

**Comment by lstocchi** [comment]
This should be fixed by #756 and it is now part of the new release 1.2.1. Closing it. 
You can find some more infos [in the documentation](https://github.com/Azure/vscode-kubernetes-tools/blob/27882d74f49c73062b818982eca198bf91d4821f/debug-on-kubernetes.md#7-nodejs-debugging).
If this is not what you were expecting or you think we still need to improve the debug for nodejs app let us know and/or feel free to reopen it. Thank you :)
