### ISSUE TITLE
Bug: Port Forwarding Only Works for Default Namespace

### ISSUE THREAD

**Issue by shreyu86** [Azure/vscode-kubernetes-tools#231]
I have been using this extension and it is awesome productivity booster. 
I noticed that port forwarding currently does not propagate the namespace (selected namespace) context to `kubectl` [here](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/kubectl/port-forward.ts#L45) and other places `portForwardToPod` is called no namespace is passed and hence the `default` namespace is used. 

Happy to work on a PR if you can point me towards the implementation you would like to see to plumb in the namespace.

**Comment by itowlson** [comment]
cc @bnookala 

Thanks for the offer to tackle this!  If memory serves, using a non-default namespace should be changing the default namespace for `kubectl` (see `useNamespaceKubernetes` in extension.ts), so the code paths from right-click (`if (explorerNode)`) and 'select from drop-down' (lines 69ff.) _should_ work correctly.  If not then we do indeed need to propagate the namespace.  Let's confirm the issue occurs in these cases, and we can provide more guidance on the implementation of these cases if you want to work on it.

However there is definitely a problem if a pod manifest is open - in this case we infer the pod name from there, but do _not_ pick up the namespace.  Fixing this probably means updating the `tryFindKindNameFromEditor` function (referenced in line 179) which will have a knock-on effect throughout the extension - but this will fix similar incorrect behaviour throughout the extension.

Let us know if you plan to send a PR for this - otherwise we will tackle it, we just don't want to duplicate effort!  Happy to discuss other details of the implementation if the above pointers aren't enough.  Thanks again!

**Comment by shreyu86** [comment]
Thanks for the response @itowlson, I can try fixing this bug:
1.  The `explorerNode` case was straightforward to [fix](https://github.com/shreyu86/vscode-kubernetes-tools/commit/fbc2a7f96a88886b6591938d8b94ad71abe2166a) I have tested this multiple times today. Let me know if I am in the right direction on this. 

2. In the case when pod manifest is open, is where I need some more pointers. Currently `tryFindKindNameFromEditor` returns `<object_kind>/<object_name>` there could be one implementation where it returns `<namespace>/<object_kind>/<object_name>` since other things (in `extension.ts`) rely on `tryFindKindNameFromEditor` wanted to get more feedback before implementing anything.

**Comment by bnookala** [comment]
@itowlson @shreyu86 

I think it's time we make `findKindNameForText` (used by `tryFindKindNameFromEditor` return an object that conforms to an interface with the three fields: `namespace`,` resourceType`, `resourceName`, and change usages as such.

Right now, we use `<object_kind>/<object_name>` because we can pass the entire string directly to kubectl without having to specify the resource type ie:

`kubectl describe pod/myCoolPod`

Obviously that's not going to work if we add the namespace into the same string.

**Comment by shreyu86** [comment]
@bnookala Thanks for the feedback, I will give that a go tonight and open an PR (WIP) for more feedback.

**Comment by itowlson** [comment]
Fixed in #232.
