### ISSUE TITLE
Explorer: Load pods not in non-active namespaces

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#267]
As @itowlson had noted, selecting a Pod in a non-default namespace from the Node tree in the explorer won't load the resource in VSCode. This is due to the way the `Load` command works (by using the current active namespace). This should be fixed such that the `Load` command is aware of the namespace resources are in, so it can load them.

**Comment by kameshsampath** [comment]
Sorry about my ignorance :(  @bnookala   can you detail more steps to reproduce this ? am not seeing this behaviour. One of the thing I observe in my setup which runs with `OpenShift`, I need to login to get access to needed namespace resources, otherwise the the extension shows error message that the user is not authorised.

**Comment by itowlson** [comment]
The issue refers to PR #252.  This PR added a view of the pods running on a node; however those pods might be in namespaces other than the active namespace, and when you selected a pod that was in such a namespace, loading its YAML failed or misbehaved.  So you won't see it in the normal pod list (because that is scoped to the namespace), only if you drill down from a node.

The OpenShift login issue sounds worth exploring - do you want to raise a separate issue for that?  I'm not sure it would belong in the base k8s extension but it would be good to understand in case a hypothetical future OpenShift extension needed an API to hook for it.  Thanks!
