### ISSUE TITLE
Error connecting to Azure / AKS

### ISSUE THREAD

**Issue by tomasr** [Azure/vscode-kubernetes-tools#301]
I'm having trouble getting the extension to work against my Azure / AKS clusters. Specifically, the Add Cluster wizard fails to recognize my Azure logon on the AZ CLI, resulting in the following error

![image](https://user-images.githubusercontent.com/16179/42604746-f4a5d046-8539-11e8-9d4f-4530fa7a2bf3.png)

I've checked that I am logged in to the azure cli and can access my resources already.

* Azure CLI version is `2.0.41`
* Operating System is Windows 10
* Code version is `1.25.0`

Is there a way to enable logging on the executed commands to check why `az` is failing for it?

**Comment by itowlson** [comment]
We don't have a way to enable logging - that "Details" section is the stderr from the Azure CLI, so there may not be a lot more we would be able to log anyway!  I saw on Twitter that you'd confirmed correct behaviour from within the Code integrated terminal; let me take a look at how we invoke the Azure CLI and see if I can see what might be different.

You mentioned resetting HOME - I don't _think_ that shoiuld matter, but just in case, could you check that the integrated terminal is using the altered HOME value?  Thanks!

**Comment by tomasr** [comment]
Yes, the integrated terminal sees my updated `$HOME` just fine.

I did notice that the code looks for `.kube/config` under `$USERPROFILE` (see https://github.com/Azure/vscode-kubernetes-tools/blob/a63c2c5a17703cc8524ccb88589d9572d5c260b3/src/shell.ts#L66), but both `kubectl` and `az` will use `$HOME` on windows, so if the two don't match, you'll look for the file in the wrong location.

That said, even copying both things to the user profile doesn't seem to make it work.

**Comment by itowlson** [comment]
Hah, we got that path thing from Brendan and I always assumed he knew best *grin*.  We can definitely take a look at that and make it always prefer `$HOME` if that's defined.

That said, the `az` login issue is happening long before we even get to looking for `kubeconfig`.  But that code affects everywhere we shell out to other tools.  So if `az` is caching a login token under $HOME and expecting to find it under $HOME, then our changing what $HOME refers to in our invocation would mess it up.  And the login token might be squirreled away somewhere non-obvious that you _haven't_ copied to $USERPROFILE.

Could you try the following test please:

* Start a new shell
* In that shell (only) map your $HOME to $USERPROFILE
* Run `az account list` in that shell.
* If it succeeds, let us know.
* If it fails, run `az login` in that shell and then retry the extension.

(The idea being to try to trick `az` to cache a login token in $USERPROFILE as well as $HOME, so that we find it despite our mangling of $HOME.)

Thanks!

**Comment by tomasr** [comment]
Interesting... that actually worked. Though honestly not sure at all why.
Since I have `$HOME` define from my PC settings, every single process lunched under my user should be inheriting it. Unless somehow when you spawn `az` the entire environment is not being propagated to the child process.

Also unexpected that I copied my whole `.azure` directory to `$USERPROFILE` before, and that didn't work (even though it should be able to read that just fine, it's all the same)

**Comment by tomasr** [comment]
I think I found the culprit. After my previous scenario work, I noticed that when I used the "Get" option it would launch an integrated shell for `kubectl` where `$HOME` is actually defined to be equal to `$USERPROFILE`.

So looking around I found this: https://github.com/Azure/vscode-kubernetes-tools/blob/a63c2c5a17703cc8524ccb88589d9572d5c260b3/src/shell.ts#L89

So the code is definitely overriding `$HOME` with the wrong value when it is spawning child processes....

**Comment by itowlson** [comment]
I'm guessing that the AD login token is cached somewhere _not_ under `.azure` and that running `az login` with $HOME set to $USERPROFILE caused a login token to be created under $USERPROFILE.  Then when _we_ ran `az` with $HOME set to $USERPROFILE (because of that shell environment code you flagged), it picked up _that_ cached login token.

**Comment by itowlson** [comment]
Hah, crossed in the post *grin*.  Yes, that's the culprit: on Windows, we are unconditionally overriding $HOME with (effectively) $USERPROFILE.  I'll get that fixed - thanks for flagging this and for helping to track it down.  Appreciate your patience and your spelunking of the code!

**Comment by tomasr** [comment]
No problem, happy to help! It's already looking useful and look forward to playing with the extension a bit more 😄
