### ISSUE TITLE
Add "--insecure-skip-tls-verify" setting

### ISSUE THREAD

**Issue by EpicEric** [Azure/vscode-kubernetes-tools#303]
With my current certificate setup, when I attempt to get any data from my cluster, I get the following error:

`Unable to connect to the server: x509: certificate is valid for <certificate_ip>, not <actual_ip>`

The `--insecure-skip-tls-verify=true` flag allows ignoring insecure certificates in `kubectl`. An equivalent setting (like `"vs-kubernetes.insecure-skip-tls-verify": false` as default) could be added to the extension to enable this configuration.

**Comment by mccrackend** [comment]
Found this issue/pr looking for a solution to a similar x509 error I was receiving.  Worked around it by  following the ideas from https://stackoverflow.com/questions/43776504/kubernetes-cluster-x509-certifcate-issue, where you make this adjustment on a per-cluster basis in your ~/.kube/config.  

In the attached PR, as @itowlson suggests, I agree the feature request of this issue is still relevant (adding a way to pass in flags to kubectl commands), but the proper solution probably lies more in that config file, or setting it per-cluster, instead of telling the IDE to use flags every call.

**Comment by itowlson** [comment]
That's really useful to know - thanks Dan.  Since `kubeconfig` supports a way to turn off TLS verification, we should arguably lean on that (so that users get a consistent experience across `kubectl` and the extension), rather than implementing our own config option for it.  @bnookala thoughts?
