### ISSUE TITLE
Support for CronJob objects

### ISSUE THREAD

**Issue by bgagnon** [Azure/vscode-kubernetes-tools#343]
Under _Workloads_, only _Jobs_ are currently shown.
There should be a section for _CronJobs_.

Also, should a _Job_ that is controlled by a _CronJob_ be excluded from the _Jobs_ list?
Or nested under that _CronJob_?

**Comment by itowlson** [comment]
Being able to expand a cronjob to see the jobs it controls sounds like a nice feature. I suggest we do that, but leave such jobs still in the job list - would that suit?

**Comment by itowlson** [comment]
Erg... I can't see a way to get a list of the jobs owned by a particular cronjob.  The job references its cronjob in `metadata.ownerReferences.name`, but I can't find a `--field-selector` to pass to `kubectl` to filter on that.  And `metadata.labels.controller-uid` does not match the cronjob's `uid`.  @bgagnon do you know a way?

**Comment by itowlson** [comment]
They considered automatically injecting a label (which would have allowed us to filter using `-l`), but rejected it because they thought the user could do it in the cronjob's job template, apparently not considering the possibility that someone might want to _programmatically_ identify created jobs in a way that worked across all cronjobs.  https://github.com/kubernetes/kubernetes/pull/59473  We are meant to use `ownerRef`... but that doesn't seem filterable in `kubectl`.
