### ISSUE TITLE
Kubernetes extension breaks file links in "Go Tests" OUTPUT channel?

### ISSUE THREAD

**Issue by brackendawson** [Azure/vscode-kubernetes-tools#389]
With the Kubernetes extension disabled the line references in the stack trace are clickable:
![image](https://user-images.githubusercontent.com/1909753/47211145-add37a00-d38c-11e8-9662-fd37639ec32c.png)

But when enabled they are not:
![image](https://user-images.githubusercontent.com/1909753/47211126-a2804e80-d38c-11e8-81c6-7fa6e63fdabf.png)

**Comment by itowlson** [comment]
That's so weird!  Apologies for the inconvenience this is causing you; I'll take a look.

**Comment by itowlson** [comment]
Okay, this seems to happen because we colourise the output channel.  The way the colouriser works is global, and appears to override the built-in linkifier.  It looks like other extensions that colourise the output channel (such as https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) have the same problem - I suspect whichever extension loads last overrides all the previous extensions _and_ the built-in highlighter/linkifier.

I think we probably need to remove the colouriser from the extension.  Unfortunately, the way VS Code loads syntaxes, we can't as far as I know make this conditional, so we can't even allow users to opt in via config.  But we don't make a lot of use of colourisation so I don't think it's a big loss!

**Comment by itowlson** [comment]
Closed via #391.
