### ISSUE TITLE
Make delete warning configurable or allow multi-delete

### ISSUE THREAD

**Issue by cmeyertons** [Azure/vscode-kubernetes-tools#397]
Having to go through the UI and delete each item one by one is especially tedious with the warning that pops up

![image](https://user-images.githubusercontent.com/19917677/47616014-0558a080-da85-11e8-85b1-c10eb09813ba.png)

**Comment by itowlson** [comment]
I assume from context that this is deletion through the tree view?  The VS Code tree view doesn't appear to support multi-select at the moment, so multi-delete isn't going to be an option.

We could add something like an "Delete and don't ask me again" button but that feels like it could leave the user in a brittle position, where a slip later on could result in an unintended deletion.  We could go further and have this as "Don't ask me again _for resources in this cluster_", so that you could live dangerously in dev clusters where there is likely to be high churn and the cost of a mistake is low, but still be safe in production clusters or other environments where accidents could be costly.  But this results in a lot of complexity, and in behaviour that may appear inconsistent and confusing.

I completely sympathise with the tedium but I don't have a good feeling for how to balance convenience, safety and development cost here... open to suggestions!

**Comment by cmeyertons** [comment]
thanks for the explanation!  yeah didn't think about the scenario where you flip the setting on and then 6 months down the road you accidentally delete something (bad news!)

I'm fine with you closing this one!

**Comment by itowlson** [comment]
Thanks for being understanding.  I'll close this for now as you suggest, and if anyone gets any bright ideas then we can definitely revisit it!
