### ISSUE TITLE
Services and Ingress tree nodes appear in two places

### ISSUE THREAD

**Issue by squillace** [Azure/vscode-kubernetes-tools#463]
Is this by design? Because there is no _natural or intuitive_ reason why there's a Kubernetes service under Network and under Services. A new user will not understand what is going on there. Is there a way to clarify this?

Windows 10, azure-cli (2.0.57), VS Code 
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

![vscodeerrormultipleservices](https://user-images.githubusercontent.com/1422718/52160081-050f0900-2663-11e9-82ce-0fbadef0edbb.JPG)

**Comment by itowlson** [comment]
This looks like a glitched merge/rebase.  It looks like @brendandburns moved Services under a new Network node on [13 December](https://github.com/Azure/vscode-kubernetes-tools/commit/7ac3e7823875483df7d49baa8015bd83a22bc573), but then had a [PR in flight](https://github.com/Azure/vscode-kubernetes-tools/commit/df3742e1f24831ea7a338542a3769807b5280eba) which was based off the old structure.  When the second was merged over the top of the first, Git did not see it a conflict (because it just looked like two lines being added and _that's fine_), and our puny mortal eyes didn't spot that it was duplicating something that had been moved.  So the second PR added the Services and Ingress nodes back where they were.

I believe Brendan's intent was that Services and Ingress should appear under Network, and should disappear from the top level.  Is that correct Brendan?  If so I can easily delete the spurious top level nodes.
