### ISSUE TITLE
Error loading config file

### ISSUE THREAD

**Issue by d4nyll** [Azure/vscode-kubernetes-tools#610]
# Problem

The extension is spewing out the following error (appears to be around once every minute):

```
error: Error loading config file "/home/d4nyll/.kube/config": read /home/d4nyll/.kube/config: is a directory
```

It is throwing the error because `/home/d4nyll/.kube/config` is a directory, and not a configuration file. However, this should not be an error because Kubernetes allows the configuration files to be split into multiple files. Indeed, from the [documentation](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable):

> The `KUBECONFIG` environment variable is a list of paths to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows.

I have set up my `KUBECONFIG` environment variable to be a colon-separated list.

```
$ echo $KUBECONFIG | tr ':' '\n'
/home/d4nyll/.kube/config/k8s-dev
/home/d4nyll/.kube/config/k8s-admin
/home/d4nyll/.kube/config/minikube
/home/d4nyll/.kube/config/do-lon1-ghost
/home/d4nyll/.kube/config/do-lon1-bud

$ node
Welcome to Node.js v12.5.0.
> console.log(process.env.KUBECONFIG.replace(/:/g, "\n"));
/home/d4nyll/.kube/config/k8s-dev
/home/d4nyll/.kube/config/k8s-admin
/home/d4nyll/.kube/config/minikube
/home/d4nyll/.kube/config/do-lon1-ghost
/home/d4nyll/.kube/config/do-lon1-bud
```

---

# Solution

- Check `process.env.KUBECONFIG` before using the default of `$HOME/.kube/config`
- Merge the configuration files together

## Proposal

_N.B. I haven't read the entire codebase in detail, so this may be the wrong place to implement it. Advice welcomed._

Right now, the configuration is first read from the [workspace configuration](https://github.com/Azure/vscode-kubernetes-tools/blob/6702b37a8a256dc7112acbabf545dc86bd009dc2/src/components/config/config.ts#L88-L90).

```ts
export function getActiveKubeconfig(): string {
    return vscode.workspace.getConfiguration(EXTENSION_CONFIG_KEY)[KUBECONFIG_PATH_KEY];
}
```

If this is not found, then it will try to [read from a default path](https://github.com/Azure/vscode-kubernetes-tools/blob/6702b37a8a256dc7112acbabf545dc86bd009dc2/src/components/kubectl/kubeconfig.ts#L64-L66)

```ts
function getDefaultKubeconfig(): string {
    return path.join((process.env['HOME'] || process.env['USERPROFILE'] || '.'), ".kube", "config");
}
```

I propose to add an additional check to [`kubeconfigPath()`](https://github.com/Azure/vscode-kubernetes-tools/blob/6702b37a8a256dc7112acbabf545dc86bd009dc2/src/components/kubectl/kubeconfig.ts#L60-L62) to also check the environment variable `KUBECONFIG` and read and merge all those files together as one before passing the configuration object to downstream functions.

```ts
function kubeconfigPath(): string {
    return getActiveKubeconfig() || getEnvKubeConfig() || getDefaultKubeconfig();
}
```

**Comment by itowlson** [comment]
Thanks for the bug report and the detailed suggestions!  I agree we should be checking that environment variable when we get the kubeconfig path.  However, I don't _think_ this is the source of the error message you're seeing.  The `kubeconfigPath` function appears to be called only from `mergeToKubeconfig`, which is called when a user right-clicks a Cloud Explorer node - not every minute as you are seeing.  We should still fix it there - I just don't think this will fix your particular problem.

For most interaction with kubeconfig, we call `kubectl config` or other `kubectl` commands.  We handle the config override by setting the `KUBECONFIG` variable _if the settings override is present_ - otherwise we simply inherit `KUBECONFIG` from the parent process.  So we should automatically be using your directory `KUBECONFIG`.

The fact that you see the error every minute makes me think this comes from the background process that checks which context is currently active.  (The purpose of this is to update schemas for YAML validation, hover, etc., according to the cluster version and any installed CRDs.)  This does a check every minute to see if the user has switched context other than through the extension (e.g. the `kubectl` command line).  I am wondering if this somewhere attempts to read the active `kubeconfig` as if it were a file instead of going through `kubectl`.  This code starts from [active-context-tracker.ts](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/contextmanager/active-context-tracker.ts).  Right now I can't see where it might be accessing `kubeconfig` directly.

Another place we try to use the `kubeconfig` path directly (and make the same mistake of ignoring the `KUBECONFIG` environment variable) is if the setting to automatically download cluster-specific versions of `kubectl` is turned on.  However this appears only to use the path string, not to attempt to read from it as a file.  (See [autoversion.ts](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/kubectl/autoversion.ts).)  This would affect you only if you set `kubectlVersioning` to `infer`, and I don't think would repeat every minute.

We also in one place do a `KubeConfig.loadFromFile` via the official Kubernetes JavaScript client.  I would assume that handles the directory case correctly though (and that would only happen when using the Explain function, not every minute).

So my suspicion currently rests on the active context tracker.  One way to verify this would be to downgrade the extension to 1.0.2 (use the `Install Specific Version of Extension` command) and see if the error goes away.  If so, then it is something we have introduced in the 1.0.3 changes and that almost certainly means the context tracker.  If you do that then please let me know how it goes!

Thanks again and I will keep digging.

**Comment by d4nyll** [comment]
Hi @itowlson I have just downgraded the extension version to v1.0.2, waited for a few minutes, and can confirm that the error messages no longer appear. I also upgraded it back to v1.0.4, waited for a few minutes, and can confirm the error messages appear again. Downgraded, and they are gone again. So it seems like what you said was correct!

**Comment by d4nyll** [comment]
I think it may be an issue with how the extension uses the official Kubernetes JavaScript client.

I tested it by creating a **`test.js`** file:
```js
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();
kc.loadFromFile('/home/dli/.kube/config/');
```

Then ran it with `node`:

```console
$ node test.js 
fs.js:126
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at KubeConfig.loadFromFile (/home/d4nyll/playground/kube-js-test/node_modules/@kubernetes/client-node/dist/config.js:65:32)
    at Object.<anonymous> (/home/d4nyll/playground/kube-js-test/test.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

So it appears `loadFromFile()` only accepts a file as the argument. I did further tests and found that `loadFromDefault()` _does_ load properly:

**test2.js**
```js
process.env.KUBECONFIG = "/home/dli/.kube/config/prod:/home/dli/.kube/config/minikube"
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
```

(I ran it in VSCode's Debug console, and can see two clusters in the `kc.clusters[]` array)

So I think it would be better to use `loadFromDefault()` over `loadFromFile()`.

> The `loadFromDefault()` has its own set of problems - if the file in the list does not exists, it will throw an error:
> ```
> Error: ENOENT: no such file or directory, open '/home/d4nyll/.kube/config/dev'
> ```
> But I think it makes more sense than `loadFromFile()`.

**Comment by itowlson** [comment]
Yes, `loadFromDefault` probably makes more sense (unless the user has set a non-default kubeconfig in their VS Code settings).  And I should dig into that to see how it handles the multi-file case so we can support that in the settings override case.  Thanks!

I'm travelling at the moment, but will hopefully get to this in a couple of weeks when I get back.  Sorry for the delay, and thanks for all the digging.

**Comment by d4nyll** [comment]
Thanks @itowlson, bon voyage!

**Comment by itowlson** [comment]
This is very weird.  We _do_ use `kc.loadFromFile`, but only in the explain subsystem, which only runs when invoked.  The per-minute thing relates to a background check for whether you have switched to a different context so we can update the expected resource schemas (according to k8s version and installed CRDs).  That does _not_ appear to use the `@kubernetes/client-node` library.  It _does_ read the kubeconfig but does so by running `kubectl config view -o json`.  There must be somewhere else that we attempt to open the kubeconfig as a file but I'm not yet seeing it...!

**Comment by itowlson** [comment]
Ugh, I'm not managing to reproduce this on Windows.  (I can confirm that the Explain command fails, for the reasons you give... but can't reproduce the error you're seeing.)

**Comment by itowlson** [comment]
Correction.  I think I have a repro now.  Was trying to reproduce it in the wrong way (the problem is not the multiple paths - it's that the _default_ path, `$HOME/.kube/config`, is a directory rather than a file).

**Comment by itowlson** [comment]
@d4nyll This may be a stupid question, but can you check in your VS Code settings and see if it contains an override for kubeconfig?  I see an error like yours when `$HOME/.kube/config` is a directory and my settings contains an override to use `$HOME/.kube/config` as the KUBECONFIG (instead of the environment $KUBECONFIG).  When I remove the override the error goes away.

**Comment by itowlson** [comment]
Okay, so here is what I have.

* I have set up the environment so that `.kube/config` is a directory, and `KUBECONFIG` is a list of multiple files under that directory.
* This appears to work without errors.
* However, if I delete `KUBECONFIG`, or override it in VS Code settings to point to the default location (which is now the directory), _then_ I see your error.  This is unavoidable because the error is coming from `kubectl` when it tries to 'read' the directory as if it were a file.
* But in that case I see your error even in 1.0.2 - not repeated every minute, but still on every `kubectl` operation, e.g. trying to load the cluster explorer or create a k8s resource.

You're clearly not in the "KUBECONFIG is not defined" situation, so the only thing I can think of is that somehow the default path (which on your system is a directory) has inadvertently gotten set in the VS Code `settings.json`.  But then I'd expect 1.0.2 not to work either, so I'm feeling a bit stumped!

If you're willing to invest more time in this, I can walk you through how to run the extension from source under the debugger, and you may be able to see where it's failing for you.  I understand if you don't fancy the idea though...!

**Comment by d4nyll** [comment]
Hey @itowlson apologies for the slow response, I am bit swamped this week. I _am_ up for in investing more time to get to the bottom of this, and will try out your suggestions and answer your questions, but it's looking more like a task for the weekend! :sweat_smile:

**Comment by d4nyll** [comment]
@itowlson to answer your question about the settings override, the only settings relating to this extension is to do with Minikube. (But I've included my whole `settings.json` in case I missed anything)

```json
{
	"workbench.colorTheme": "Night Owl",
	"explorer.confirmDragAndDrop": false,
	"editor.tabSize": 2,
	"window.zoomLevel": 1,
	"python.disablePromptForFeatures": [
		"pylint"
	],
	"files.autoSave": "off",
	"workbench.iconTheme": null,
	"workbench.editor.showIcons": false,
	"editor.overviewRulerBorder": false,
	"explorer.openEditors.visible": 0,
	"explorer.decorations.badges": false,
	"terminal.integrated.fontFamily": "'Fira Mono'",
	"editor.fontFamily": "'Droid Sans Mono'",
	"npm.enableScriptExplorer": true,
	"workbench.startupEditor": "none",
	"debug.node.autoAttach": "on",
	"workbench.activityBar.visible": true,
	"workbench.editor.labelFormat": "short",
	"files.exclude": {
		"**/.git": true,
		"**/.classpath": true,
		"**/.project": true,
		"**/.settings": true,
		"**/.factorypath": true
	},
	"javascript.updateImportsOnFileMove.enabled": "always",
	"search.usePCRE2": true,
	"vs-kubernetes": {
		"vs-kubernetes.minikube-path": "/home/d4nyll/.vs-kubernetes/tools/minikube/linux-amd64/minikube"
	},
	"go.useLanguageServer": true
}
```

**Comment by d4nyll** [comment]
:sweat_smile: It's late but I can't sleep without digging into it a bit more! So I upgraded the extension to v1.0.4 and it's giving me a better error message:

```
W1001 23:53:12 808668 17837 loader.go:223] Config not found: /home/d4nyll/.kube/project-x-kubeconfig.yaml error: error loading config file "/home/d4nyll/.kube/config": read /heom/d4nyll/.kube/config: is a directory
```

This bamboozled me because Project X was a very old project, and `/home/d4nyll/.kube/project-x-kubeconfig.yaml` no longer exists. I checked the `KUBECONFIG` on my terminal and by looking into `.bashrc` - nothing that mentions `project-x`. I use `ag` to search for `project-x` - again, nothing.

I then looked up [`loader.go:223`](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#L223) and it seems the _real_ error is that the configuration file doesn't exists, _not_ because it is a directory. Which fits what this new error message is telling me.

So it turns out, I've set `/home/d4nyll/.kube/project-x-kubeconfig.yaml` as part of the `.profile` :man_facepalming:, and since VS Code doesn't run in an interactive shell, it doesn't use the `KUBECONFIG` set in `.bashrc`.

```
export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/project-x-kubeconfig.yaml
```

From the onset, I made the (wrong) assumption that it's the directory issue and nothing else, and lead you in the wrong direction. But thank you @itowlson very much for spending so much time on trying to get to the bottom of this issue, and sorry that it ended in such an anticlimactic way.

**Comment by itowlson** [comment]
Oh no!  Thank you for closing the loop on this one - I'm almost disappointed that it turned out to be a configuration error at your end - it would have been a very satisfying bug to fix!  But having it working for you is the most important thing!
