### ISSUE TITLE
Array.prototype pollution causing interactions in other extensions

### ISSUE THREAD

**Issue by MikeRalphson** [Azure/vscode-kubernetes-tools#613]
I've had a [couple of reports](https://github.com/Mermade/openapi-lint-vscode/issues/9) of `Array.prototype` pollution which we have narrowed down to this extension, a quick search points to this code probably being the culprit:

https://github.com/Azure/vscode-kubernetes-tools/blob/070b7d4278b13f2d24fa17c5fb2ccc208becaf30/src/utils/array.ts#L16

Is it possible this function could be made non-enumerable, or some other workaround employed?

**Comment by itowlson** [comment]
Thanks for flagging this.  The shared extension host process can be a pain - apologies for the impact this has had on you.  I'm travelling at the moment and won't be able to get to this for a couple of weeks I'm afraid.

Can you clarify how it results in the issue in your extension?  The easiest fix (converting it to a toplevel function instead of a method) will make it fiddlier for me to work with, so I'm wondering if I can get away with something else.  But it's not obvious to me how this might be causing your symptoms, since you presumably aren't also adding  a `choose` method to arrays...!  Thanks!

**Comment by MikeRalphson** [comment]
Hi @itowlson - in my extension I'm creating plain JS objects (containing arrays) from the contents of the editor and passing them to an OpenAPI validator/linter. The validator isn't expecting additional enumerable properties on arrays (it could be coded more defensively, but this would be a lot of work and reduce code readability) and is so blowing up when it hits the unexpected function.

I've added a work-around for now to my extension which 'cleanses' the Array.prototype by redefining any enumerable properties it finds on an empty Array, using `Object.defineProperty`.

I'm also travelling from today, but could probably do a PR next week which defines the `choose` function as non-enumerable initially.
