### ISSUE TITLE
Update Kubernetes Clusters View content automatically when something changed

### ISSUE THREAD

**Issue by dgolovin** [Azure/vscode-kubernetes-tools#647]
Current implementation for Kubernetes Clusters view shows only snapshot of resources that was taken at specific time. 
Every time after resource is created Clusters View should be refreshed and then sometimes searched for that new resource.
It works when you need to do something once, refresh and then keep working on your code. 
When you doing something that creates kubernetes resources frequently it slows you down.

Lets look at Tekton - a kubernetes-native pipeline resource - as an example.

Current Cluster View API lets you easily add new ResourceContainers to the tree, so after a little work we can have Cluster view looking like one below

![image](https://user-images.githubusercontent.com/620330/68502078-7b552300-0214-11ea-9e03-7a8316b644a3.png)

Every time I start tekton pipeline to do something with my application nothing is going to be changed in the tree. 
**I have to refresh it** to see piplinerun created, first step in pipeline started and represented with TaskRun resource. 
Pipeline usually consists of several steps to see progress **I have to refresh it** several times while pipeline is in progress. 

Would be good to have a view that can listen to changes in resources and update the content of the tree accordingly.

**Comment by itowlson** [comment]
Related: #398 

There are two issues here: performance and visual stability.

The performance issue is that right now we don't have any infrastructure for refreshing only part of the tree.  The VS Code API does provide for this, but we don't currently make use of it.  So updating the tree means refreshing the _whole_ tree - and that takes a while.  We can tackle this, but it involves a bunch of work:

* Subsystem to monitor the cluster for changes - we can get some of this from the Kubernetes JS client but would need to build on top of it to produce a suitable feed that we can feed into the change event mechanism.
  * Would this be desired-state or event-driven?  Desired state means diffing against current state; event-driven means events could be missed.  A combination of the two solves this but requires extra effort.
* Implement the change event mechanism - detect what has changed and locate the appropriate part of the tree to update.  Not sure what's involved here but our tree structure is pretty weakly defined so this might be non-trivial.
* Figure out how change detection plays with the API, e.g. if a CRD changes then do we notify all registered contributors and customisers so they can do their thing?  What if this involves drama?

The other side of the coin is the user experience, specifically visual stability.  In a fast-changing cluster it could be vexing going "I want to look at pod X" but it keeps moving around because pods A-W keep appearing and disappearing.  And we don't want someone to be about to right-click > Delete a resource and have the tree shift underneath them just as they are clicking the mouse.

Arguably users cope with the occasional file coming or going, but in the context of a personal computer that's usually because they have done something that is creating or removing the file - pointing VS Code at a busy network share might be more frustrating/distracting.  But also dev clusters are likely to be fairly quiet and probably not too widely shared.  And we could easily provide a setting to turn off the live updates (or a command to suspend them).

So the UI issues are probably fairly easy to solve.  The changes to make it performant will be I think be rather more difficult.  I'd love to explore it further though.

**Comment by sandipchitale** [comment]
One heuristic that could be used for optimizing the refreshing could be that - if the Cluster changing action originated from the VSCode Kubernetes extension context and the affected nodes are expanded in the tree, then refresh those. For example if I use **Delete** or **Delete Now** commands on a Pod, do a refresh on the Pods node. Of course the user may use kubectl command in a termnal or install/upgrade a helm chart which may affect the Cluster, that may not be trackable.

**Comment by lstocchi** [comment]
Closing it as https://github.com/Azure/vscode-kubernetes-tools/pull/686 was merged
