### ISSUE TITLE
logs display too long

### ISSUE THREAD

**Issue by vacheli** [Azure/vscode-kubernetes-tools#737]
Hi guys
I use "Follow logs" to watch application log, Some logs display too long.
![image](https://user-images.githubusercontent.com/5040231/79835708-c0939880-83e1-11ea-869b-63f75969359d.png)

**Comment by itowlson** [comment]
Is this because the actual log message is indeed very long, or do you suspect we're joining lines together?

If the actual log message is very long, what is the desired behaviour?  We should be careful about word wrapping because that could make it look like one log line is several distinct messages, but perhaps worth considering....

**Comment by vacheli** [comment]
Similar kubectl logs -f, that can be displayed in new line for easy viewing. It really takes a long time to view the log when it is very long.

**Comment by ionutrusuboca** [comment]
Hi. I am experiencing the same thing. I believe it's just that the line is very long and I can't find a readily available way to wrap it within the visible area. 

I see these options at the top : 'Show log entries' ; 'Match expression' then 'Scroll To Bottom' . Maybe a 'Wrap lines' would be a nice addition ? :) Thank you .

**Comment by lstocchi** [comment]
Closing it as new log viewer has been merged and released. Please open new issues if you face any problem or have some ideas how to enhance it. Thank you!!
