### ISSUE TITLE
Tips for using the extension when running Bastion Hosts

### ISSUE THREAD

**Issue by tvvignesh** [Azure/vscode-kubernetes-tools#762]
Hi. This extension worked really well when my Kubernetes Cluster was public. But recently, I have migrated to Private Kubernetes cluster with even masters not accessible from public. 

The only point of access is through SSH via a Bastion VM. In such cases, may I know how I can still use this extension when I am using a jump server to connect to my cluster?

Thanks.

**Comment by itowlson** [comment]
For the most part, the extension invokes `kubectl` to do its work.  So if `kubectl` is able to see the cluster then the extension should be able to as well (except a few bits that need to hit the API directly).  What is your configuration - you need to ssh to the jumpbox and run kubectl there?  Are you able to install VS Code Remote on the jumpbox?  If so, I believe you can run the VS Code UI on your GUI machine and have it talk to its 'back end' (files and extensions) on the remote via SSH.

**Comment by tvvignesh** [comment]
@itowlson Thanks a lot for your quick reply. While I should be able to use VSCode Remote on the jumpbox, wanted to know how I can set this up not just for my use but for multiple developers like me. Should I be doing some sort of ssh forwarding for Kubectl?

I am thinking of using Google Cloud IAP and use this Terraform module to connect to the Bastion Host via IAP (https://github.com/terraform-google-modules/terraform-google-bastion-host)

What approach would you recommend when there are multiple developers accessing a remote K8 cluster in the team via Bastion? Thanks.

**Comment by itowlson** [comment]
I'm not familiar with Bastion Hosts so I would need to do some research and testing and I can't make any promises when I could do this.  What I can tell you is:

* Most of the extension just needs to invoke `kubectl`.  So what you need is a viable `kubectl` on the box where the extension is running.
* If you can configure `kubectl` on your team's machines to tunnel via the jumpbox (by whatever means), then that should work.
* If you can only run `kubectl` on the jumpbox, then you would need VS Code Remote running on the jumpbox.

From a quick read of the docs it sounds like your IAP approach might work but I am still not sure how local `kubectl` would reach through the SSH tunnel - but if you know how to do that, and can make it transparent, then it _should_ work find with the extension.

Tagging as `help-wanted` because this is beyond what I know about - @lstocchi @squillace does either of you know anyone who might have experience with this configuration?

**Comment by tvvignesh** [comment]
@itowlson Sure. I will give it a try. Thanks a lot for your elaborate reply. You may close this issue :-)

**Comment by lstocchi** [comment]
No i don't have any experience with it :( 
@tvvignesh let us know if you find a way to make it work otherwise we can investigate about it ;)

**Comment by squillace** [comment]
It's basically Jumpbox as a service in Azure. Because the extension is kubernetes-centered and doesn't contain any distribution dependencies or cloud dependencies beyond those required to run (for example, VS Code!!!!), the thing to figure out is how to make kubeconfig itself be able to hit the cluster. You do that, and the extension can do it.

BUT if there's a special thing you have to do with Azure Bastion, for example, then it would make sense to create a custom extension for Bastion using the VS Code Kubernetes Extension API; that way you could customize your Bastion experience but we don't modify the underlying opensource extension.

If you DID do that, I'd be happy to connect you with the Bastion people so that they can help out. :-)

**Comment by tvvignesh** [comment]
Thanks a lot for all your replies. I am trying it out. Will reply back to this thread soon with the solution I think would be optimal soon.

**Comment by tvvignesh** [comment]
@itowlson @lstocchi @squillace After a lot of research and testing, found out an elegant and secure way to do this (While this was tested in GKE, it should be applicable to other cloud providers as well except for the gcloud command). Providing the instructions below.

This allows kubectl to access the GKE cluster through bastion host running behind IAP. 

# Inside the bastion host

## Start kubectl proxy server in the background

kubectl proxy --port=8080 &

## Test it inside the bastion

curl http://localhost:8080

# In the machine accessing the bastion host

## Start a gcloud ssh tunnel through IAP and port forward the relevant port

gcloud compute ssh bastion-vm-name --project project-id --zone zone-name -- -L 8080:localhost:8080

## Configure kubectl to use the new API server URL

kubectl config set-cluster default-cluster --server=http://localhost:8080

kubectl config set-context default-system --cluster=default-cluster

kubectl config use-context default-system

## Work is complete. Now test it

kubectl get pods

**Comment by itowlson** [comment]
Glad to hear this is now working for you @tvvignesh!
