### ISSUE TITLE
Kubernetes: Run failed with no further direction

### ISSUE THREAD

**Issue by akaroml** [Azure/vscode-kubernetes-tools#77]
Tried Kubernetes: Run and got the notification:
<img width="466" alt="screen shot 2018-03-09 at 11 07 09 am" src="https://user-images.githubusercontent.com/16755094/37188490-60291b28-238a-11e8-9d71-83dd4ae173f6.png">

And here's the message in Output window:
<img width="389" alt="screen shot 2018-03-09 at 11 06 10 am" src="https://user-images.githubusercontent.com/16755094/37188480-547ccb3a-238a-11e8-91e9-6d09cdf4d505.png">

It would be nice if we can provide further directions to resolve the problem. I could not tell the cause from the error message.

**Comment by itowlson** [comment]
That's the error message from Docker.  I'm not sure we _have_ any more information.

Can we come up with any heuristics for 'if this error occurs then we can check X, Y and Z, and flag any violations to the user'?  I think I've seen this if the Docker user ID isn't configured on the extension, so that could be a thing to check.

**Comment by itowlson** [comment]
Do you have `vsdocker.imageUser` configured in your VS Code settings?  If not, can you set it please?  If that solves the problem then we can add a heuristic to check it in the event of a `docker push` error.

**Comment by akaroml** [comment]
This works! I can proceed but got another error:
<img width="480" alt="screen shot 2018-03-09 at 11 32 14 am" src="https://user-images.githubusercontent.com/16755094/37189228-2cf1001e-238e-11e8-80d5-d1736c1f9523.png">

I guess this should not happen on a first run.
