### ISSUE TITLE
Provide extensions recommendation based on installed CRD 

### ISSUE THREAD

**Issue by evidolob** [Azure/vscode-kubernetes-tools#772]
`vscode-kubernetes-tools` can provide recommendation to install extensions base on current k8s  cluster CRS's.
This mostly the same as [Workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions), but instead of letting user configure that we can provide recommendation list.

Requirements:

- Flow and behavior is mostly the same as `Workspace recommended extensions`, first we show dialog that we have recommendations for current cluster, if `Show` button clicked, we show tree view with list of recommended extensions.
- Recommendations can be turn off in preferences
- Dialog shows only once when extension connects to new cluster
- Dialog not appears when there are all recommended extensions installed

We can have that recommendation list in JSON file, format example:

```json
{
    "crdApiToExtensions": {
        "CRD.API.value": [
            "some.vscode-extenion-id"
        ],
    },
    "extensions": [
        {
            "id": "some.vscode-extenion-id",
            "label": "Cool  Extensions",
            "description": "Description to the Cool Extensions",
            "icon": "https://path/to/icon.png"
        }
    ]
}
```

I have made a prototype of this:
![ezgif com-video-to-gif (15)](https://user-images.githubusercontent.com/929743/83023536-b3e40f00-a035-11ea-88b8-085d4903f24c.gif)
so I can provide a PR with this feature.

**Comment by lstocchi** [comment]
What do you think @itowlson ?

**Comment by itowlson** [comment]
This is a really interesting idea.  We'd need to maintain a (user-curated) mapping of CRDs to extension recommendations, and figure out how to make it Not Annoying.

I'm actually wondering if this is something that could be done using the API, external to the core extension.  That might make it easier to maintain and would mean it could ship on its own cadence as users contributed new recommendations.  But it would also make it less easy to discover.

cc @squillace for Giant Marketing Brain

**Comment by squillace** [comment]
OK, originally I read this and started thinking, which required a bunch of drinking first, so now I'm back. 

I think, in so far as CRDs are "cluster role services", it makes some sense to enabling this kind of functionality. The user story is that they:

- connect to a cluster
- the extension sees "known" CRDs and prompts for related lookups
- user has configurations to control this

Does that sound about right?

**Comment by evidolob** [comment]
@squillace Yes it does.

**Comment by squillace** [comment]
I'm wondering whether the experience can be fleshed out a bit. I would NOT expect to get prompted for every one of the 32 CRDs my ops cats put into the cluster I'm using; instead, I'd be happy if my OpenShift extension detected OS-related things and prompted for those -- yes?

I do not expect the OSS core extension to do specific jobs on any/all CRDs that exist out there two years in the future. If there's one thing that this container crap has taught me, it's that whatever you think makes sense NOW makes no sense in the scale-out future, in which each object is abused by every developer because _it's the only way to make things work_ and there are CRDs everywhere.

So, with my two-year-future hat on, I see hundreds of CRDs in half the clusters or more. Generically prompting seems like a bad way of doing this. Instead, I'd think we'd provide a prompting mechanism in the extension api that wasn't visible without any child extension taking advantage of it. As a user, I despise getting prompted for things when I install fresh and haven't made any choices yet, and I have never met one that doesn't feel this way. 

The problem here is that how could the user know to install things that will themselves recognize something the user doesn't already know is in the cluster?

We could prompt for a CRD recognizer extension IFF we detect any CRDs in the cluster, for example. Hey, you have CRDs that might be associated with applications. If you want, we can install the CRD-detector extension to help you interact with your custom resource descriptions if you click here...."

But even if we do that, I'm not clear we have any plan to host some service that keeps this stuff up to date. We could crowdsource it and have it be a json list in this repository, for example, which would require us to accept PRs to add to the list. Is there any other way envisaged of handling the crush _in the future_, as opposed to now?

**Comment by jeffmaury** [comment]
The idea is that you can associate an extension against several CRDs but the extension will be selected as soon as one of the associated CRD is present on the cluster so the user will see only a list of proposed extension no matter how may CRDs selected that extension.
For example the Tekton extension will be associated against `tekton.dev` and `triggers.tekton.dev` and if the cluster has both Tekton Pipeline and Tekton Triggers installed, he will be proposed the Tekton extension once

**Comment by lstocchi** [comment]
I think @squillace is more worried about how to handle and keep updated the "recommended extensions" list and he wanted to know if someone could provide another idea besides of keeping a list here and accepting new PRs to add new stuff to the list as we could end up having xxxx recommended extensions.

The problem could be that if we add an extension to the list now, what happens if it stops to be supported in the near future? Who is responsible to decide that that extension has to be removed? Do we need to check all extensions in the list every x months? Or, if you add an extension X to the list that support Y and Z CRDs, what if someone else create another extension for Y and Z? how do we decide which is the best extension to recommend? Do we add all extensions (we receive from the community) to the list without any check?

Hope i interpreted your message correctly @squillace 

For the record, i don't see any other way to manage it, maybe we could ask VSCode guys for some suggestions. Do you know how the "Other recommendations" section works? How do they pick the extensions there?

**Comment by squillace** [comment]
@lstocchi you've pretty much got my thinking. Only problem with this now is that I, personally, and everyone else I know as a user HATES THE SUGGESTIONS FEATURE. Only companies like the suggestion feature. :-| Suggestions at the global level are mostly anti-user. 

@jeffmaury you're on the right track, but in your example the only way to do this is if some extension is tracking CRDs against some list, and that some list must be maintained and supported not today -- that's easy -- but against some future world in which a cluster is MORE CRDS THAN ACTUAL SERVICES.

There is no inherent reason for anyone here to expect that K8s will remain a majority "organic" services. I can foresee a future that is not far off from today in which RH customers - to take a specific example that makes complete sense! -- all build NOT services but operators for everything they do, right?

Now, let's say that catches on! Everyone does it. Now, _in this world there are only CRDs floating around your cluster, pretty much._ As the RH world, for example, loves operators, if we envision a world like that being all the rage, then this functionality blows up and we have to end up disabling it because there's no way to manage it (the service backend isn't the problem). 

I'm fairly sure that this is actually a great example, because it's an objective of RH and helps RH's customers right now! (Mind you, I love operators and CRDs equally -- I think they're a necessary but very bad idea and it will end up being a complete mess within about three years. Just to get my cards on the table. :-) )

In this operator-centric world, you're going to end up turning off this feature, and probably ripping it from the extension. Your users want to know what RH-centered CRDs they might have, _not recommended CRDs generally_. At least, this is my assertion -- untested!!! So the user story I'm thinking has this _assumption built into it_: users only want to know about possible extensions **once they're inside of a developer or operator context**. 

So my story works like this:
- I install VS Code, and grab a repo and likely I already know it's an OpenShift story environment so I install the RH OS extension pack or whatever. 
- THAT extension pack knows what other associated CRDs can expose a richer experience with another extension, so if RH extension sees tekton, for example, it then prompts for the tekton extension. 

So these are the presuppositions I'm bringing to the table here, and I trust that by being explicit about my own biases you can better decide whether my argument holds weight. :-) 

If we prompt generally, that means:
1. we have to build a backend that will go out of date in any number of ways and maintain it (though it could be as easy as a static file in this repo)
2. we are helping torture the mass user every time they connect to a cluster by assuming they have no idea at all what "type of environment" it is
3. I assume this will lead to what most devs I know do, which is to turn off prompting first thing.
4. as CRDs (in the example above, led by the explosion of operators!!!) increase as "regular" workloads, the prompting becomes completely useless _except as above, in which a set of them naturally run together in particular environments_. 

Whatchya think? Tell the truth: is my argument persuasive, or unpersuasive? I'm not clear I'm right at all, I'm just trying to be completely transparent about my thinking. (And remember my bias: I believe that cluster-wide lifecycle operations are a bad forward plan for k8s; we might as well build native services on VMs which are a far more well-battle-tested mode of delivery. No knock on RH operators or OS, because I know you're all battle-testing them right now. :-) )

Hope all this helps! No decisions made here yet, so no worries on that score.

**Comment by squillace** [comment]
BTW, I'll take up how the global suggestions feature works and the choices made with it with Chris Dias and the Code team, just to understand how they see the very same problems....

**Comment by gorkem** [comment]
I also share the concerns about the helpfulness of suggestions on vscode especially when they are driven by filename extensions and pops up everytime. I am looking forward to the feedback from the code team. However if you look at the screenshot provided by @evidolob his prototype is much subtle and better suited for our purpose. It is a recommendation view that changes as kube contexts change.  As suggested, a developer may not be aware of what is available on the cluster and this is exactly what is different from local files. We can help with that discovery and match them with tooling and provide it as a non-intrusive view on the extension.

**Comment by squillace** [comment]
Good comment. I went back and took a good look at what's going on here, and I realize that the thing I hate is the pops _which mandate interactivity and distraction_. You MUST click those toasts to dismiss them, and you cannot un-see them. (Until you're angered and switch them off, which you will immediately do.) BUT......

....the relatively subliminal left hand pane once @evidolob does click the toast seems very easy to me. I **could** feel good if we figured out a way to prevent forcing my interaction with the environment and yet suggesting to the user than there might be more beauty available. I'm wondering whether we could think about how to automatically suggest possibilities in the left pane, and not with a toast. 

What do we think about those kinds of possibilities?

**Comment by gorkem** [comment]
I guess the toast notification is not adding as much value. Perhaps we can implement this without the notifications. @evidolob WDYT ?

**Comment by evidolob** [comment]
@gorkem Yes, I can. I will provide a draft PR with this, just to have a discussion on real behaviour.

**Comment by evidolob** [comment]
@squillace @gorkem I add draft PR, and new demo gif in it.

**Comment by gorkem** [comment]
@squillace @itowlson did you check the latest demo gif. Should we complete the draft PR?

**Comment by squillace** [comment]
No, I hadn't. My apologies as you've all been working hard on this stuff. I can only plea worldwide epidemic disruptions to the life. I will look at this today with some purpose.
