### ISSUE TITLE
Refactor logs view 

### ISSUE THREAD

**Issue by lstocchi** [Azure/vscode-kubernetes-tools#828]
Opening this as a remainder bc I closed https://github.com/Azure/vscode-kubernetes-tools/pull/773. The guy who opened that PR is not able to work on that anymore.

Description of the new logs view at https://github.com/Azure/vscode-kubernetes-tools/pull/773#issuecomment-648544485

**Comment by tvvignesh** [comment]
@lstocchi @itowlson I guess adding colors to the log would add a lot of usability. Currently, its difficult to distinguish log levels or other messages during development cause of this in web view.

![image](https://user-images.githubusercontent.com/1165845/100925985-beadbe00-3508-11eb-9318-0f858046b1a0.png)

**Comment by lstocchi** [comment]
@tvvignesh I agree. Hopefully i should have some free time in a week to start working on all the enhancements asked for the log webview. :crossed_fingers: ...and sorry for the lack of updates on this.

**Comment by sdwerwed** [comment]
This freezes my VS Code because logs are too big, RAM and CPU are getting too high (and wouldn't blame the laptop, it is a good one).
Could we give it a bit higher priority as it is not just an enhancement, it will prevent issues like this. 

(I never coded in this typescript so not sure how much helpful I would be here)

**Comment by lstocchi** [comment]
Closing it as new log viewer has been merged and released. Please open a new issue if you face this or other problems. Thank you!!
