### ISSUE TITLE
kubectl config view -o json process hanging with 100% CPU usage

### ISSUE THREAD

**Issue by carumusan** [Azure/vscode-kubernetes-tools#843]
Intermittently seeing 100% CPU usage and tracking it back to a hung kubectl process.

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

❯ file $(which kubectl)
/usr/local/bin/kubectl: Mach-O 64-bit executable x86_64

Code Exploration Version
Version: 1.52.0-exploration
Commit: a31f124319d43aef2e9d8b875015d11a53c6f541
Date: 2020-11-27T03:15:25.043Z (4 days ago)
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0
```

It is hanging on both Code Exploration and the production version of Code. I'm using the KUBECONFIG to set a custom path in the terminal if that could be related. I don't use the default ~/.kube/config and that file doesn't exist.

**Comment by itowlson** [comment]
A few questions to help us try to track this down:

* Does this only happen when you issue a command, or does it sometimes happen just out of the blue (i.e. due to the extension running kubectl in the background)?
* If it only happens when you issue a command, are there any commands that are more prone to it than others?
* If it happens in the background, does it tend to happen around extension startup, or does it happen any time?
* Are you able to identify the full command line and environment of the `kubectl` instance that is hanging?  I see it is `kubectl config view -o json` but I'm wondering what it thinks the KUBECONFIG is at that point (whether it has one passed on the CLI or via the environment variable).

Thanks for your help!

**Comment by carumusan** [comment]
I no longer experience this bug since updating to MacOS 11.1. It's possible that it was a bug in the Rosetta 2 translation layer as I'm running on the m1 processor. 

To answer your questions it happened in the background not on startup. KUBECONFIG was a list of files and no ~/.kube/config file. I didn't knowingly trigger the command it must have been triggered indirectly by the extension. It happened roughly once a day or around that frequency and I noticed when the battery was draining quickly.

**Comment by itowlson** [comment]
Thanks for the additional details.  If it's no longer happening then I'll plan to close it.  Let us know if you would like us to leave it open and investigate further.  Thanks!

**Comment by carumusan** [comment]
Good to close. May be useful info if it occurs in future.
