### ISSUE TITLE
Disable update notifications

### ISSUE THREAD

**Issue by alexreg** [Azure/vscode-kubernetes-tools#861]
Given I use macOS's Homebrew to install and automatically Minikube and Helm, I don't really want these notifications appearing every time I open a new VS Code window.

<img src="https://user-images.githubusercontent.com/67036/105641610-d48e8e00-5e7c-11eb-99b7-210ad9472caa.png">

Is there any way to turn them off? If not, could you kindly add a new setting to do so?

**Comment by itowlson** [comment]
The setting you're looking for is `vs-kubernetes` > `checkForMinikubeUpgrade` - hope this helps and please let us know if not!

**Comment by alexreg** [comment]
@itowlson Thank you; I believe believe that solves my problem!

Does the extension check for Helm upgrades too, or not? (If so, it would make sense to add a `checkForHelmUpgrade` setting too.)

**Comment by itowlson** [comment]
Great, glad that helped.

We do not check for Helm or Kubectl upgrades.  We will offer to install those if we find them to be missing when we need them, but if they are present we will just run with whatever version you have.  

_Exception:_ There is a (currently opt-in) config setting where you can have us automatically run the version of Kubectl that corresponds to your active cluster (because Kubectl is not very compatible across cluster versions).  However, if you do opt into this, it is silent - it does not bug you with notifications or ask you to do the download - it just downloads any new versions it needs and gets on with the job.

Minikube is therefore a bit of anomaly in that respect, and, now that Minikube is more mature, perhaps we should remove the push to keep up to date...

**Comment by alexreg** [comment]
Okay, that all sounds reasonable, cheers.
