### ISSUE TITLE
Allow adding kubernetes cluster installed on local network with kubespray

### ISSUE THREAD

**Issue by CodingSpiderFox** [Azure/vscode-kubernetes-tools#923]
For my homelab, I have 3 Kubernetes Clusters: dev, staging, prod

I want to be able to add them easily via the GUI in VSCode. 

Please add an option to not only be able to add Azure clusters or Minikube but also clusters bootstrapped with kubespray

**Comment by itowlson** [comment]
Does kubespray provide a way to add these clusters to your kubeconfig?  As long as you can do that you don't need to use the wizard.

If you're interested in a more integrated experience, then the way to go about it is to create a kubespray cloud provider (so that your kubespray clusters would appear in the Clouds pane and could be added to your kubeconfig from there).  I'm not familiar with kubespray but I'd be super happy to support anyone interested in building such a thing - documentation is at https://github.com/Azure/vscode-kubernetes-tools/blob/master/docs/extending/cloudexplorer.md if you or anyone in the kubespray community would be interested!

(By the way, the wizard is being deprecated in favour of the Clouds pane.  We don't be adding any new providers there and will be removing it at some point in the future.)

**Comment by CodingSpiderFox** [comment]
OK thanks for the info
