### ISSUE TITLE
Log view filling up very slow for larger logfiles

### ISSUE THREAD

**Issue by Xan2063** [Azure/vscode-kubernetes-tools#942]
Hi everyone,

first of all thank you for providing such an improved log exploration experience with the new release. 

I have some issues while digging into "large" logfiles (>2MB). If I try to follow that file from the beginning, it takes ages until the log is loaded and continues to follow the log. 

If I use the tail option for the last 500 lines, scrolling is nearly instant. 
Filtered output is a bit faster.

But if the logfile gets larger the ingest of that logfile seems to be much slower and it takes 10 minutes until the log is read. The same operation takes a few seconds on the normal terminal.

Are there any settings in vscode to improve that behavior?
Thanks for your efforts

**Comment by lstocchi** [comment]
Thanks for opening this @Xan2063. I'm giving it a look. Unfortunately i don't think there is any setting you can change to improve this. I'll keep you updated.

**Comment by lstocchi** [comment]
Hi @Xan2063, i created a PR with a possible solution. Could you please give it a try and tell me if it works for you? https://github.com/Azure/vscode-kubernetes-tools/issues/942
Everything is explained there. If you want i can also create a vsix for you, just let me know.

The result is really dependent on the user machine so a feedback from you would be extremely helpful. Thanks!!

**Comment by Xan2063** [comment]
I can check this on monday. Is there an easy way to patch the current installation?

**Comment by lstocchi** [comment]
> I can check this on monday. Is there an easy way to patch the current installation?

The fastest way is to debug the PR or create a vsix from that one and upgrade the installed extension.
I created this vsix https://github.com/lstocchi/vscode-kubernetes-tools/blob/master/vscode-kubernetes-tools-1.3.2.vsix . You can use this one if you want. 
You should be able to see if the upgrade successfully worked by checking the log viewer toolbar, if you see the new `enable highlighting` option, you are using my fix
![image](https://user-images.githubusercontent.com/49404737/118453955-170ffb00-b6f8-11eb-9eec-c3763dbfad0c.png)

**Comment by Xan2063** [comment]
Hi @lstocchi,

I tried your changes. Now I can see nothing until the log is fully loaded which takes something like 11s for 10000 lines or 40s for 100.000 lines. The scrolling experience without highlighting is nearly instant, with highlighting it stutters directly after loading but reaches the same level after some seconds. Is there a way to introduce paging to the initial loading?

Thanks for your efforts

Do you need any logs or something else?

**Comment by lstocchi** [comment]
Hi @Xan2063 

Thanks for your quick response. 
Unfortunately I don't think we can do much more or atleast i don't have many ideas to optimize the loading time of 20x. The outcome really depends on the machine the developer is working on.
We build our webview by appending HTML elements, right now there is no optimization on the numbers of tags created (we add a tag to color words) but even if we work on it i don't think we will reach the huge optimization we need. BTW i will try.

Regarding pagination, it really depends what you mean. If you actually wants to have multiple pages, and have buttons to switch from page 1 to 2, 2 to 3, and so on .... it is feasible but i guess it will lead to a bad usability, mainly when following logs.
If by pagination you mean loading few X rows so that the page doesn't freeze up, you also have to consider that the loading time will get worse with it. To not freeze the page you cannot draw continuously in loop but you need to stop a bit before each rendering to prevent the UI thread to being too busy and also the html rendering engine is more powerful when drawing big chunk of code rather than many small ones. 

Is it better to have the webview frozen for some time and then have everything working or have the webview unfrozen but wait minutes before to see the end of a huge log? We also have to consider that without highlighting the outcome is almost instant, so if users choose to highlight logs they should be aware they need to wait a bit. Also it really depends on the machine, in my case to load 80k it takes 6sec. So not sure what to do right now, i need to think about and test other optimizations.

@itowlson any ideas on it? BTW i see the PR took some improvements and maybe it's worth to be merged as it is.

@Xan2063 thanks again for your help. I will bother you again as soon as i have something new to test :)

**Comment by Xan2063** [comment]
Hi @lstocchi,

I checked with the follow option activated and then the log is really struggling to fill. It starts immediately to fill but takes several minutes for 10000 lines regardless of the highlighting option.

I think the machine I work on should not be a problem, it is a i7 with 32 GB RAM, could it be latency to the cluster? Pipeing the result to a file is pretty quick. 

With pagination I meant the latter not the one with the real pages. I think you could render an area of ~100 log messages and maybe 100 more above and below that one to give your renderer some time while scrolling. My log reading normally is more like jumping somewhere (either the end or some search result) and then starting to scroll from there but with a speed where I can still read at least parts of the messages.

Happy to try something out if you need something.

Thanks
Alex

**Comment by lstocchi** [comment]
> I think the machine I work on should not be a problem, it is a i7 with 32 GB RAM, could it be latency to the cluster? Pipeing the result to a file is pretty quick.

No, your machine is definitely not the problem. 
This rings a bell. I created a pod which generates huge logs for testing, i guess it makes long logs but they match few regex rules and this impacts on the results i have. Otherwise i cannot explain the difference in the rendering time we have. I will also try to change it and see if i can achieve your results.
Thanks for the feedback and the hints. I'll ping you when i have something working. :+1:

**Comment by lstocchi** [comment]
@Xan2063 I'm very close to have a working viewer with the enhancement you suggested. Everything seems working fine for me but i wanted you to give it a look with your huge logs and see if the experience is better or you face any other issue. I still need to fix some minor things but the logs rendering should be complete.
Could you please test it whenever you have time and let me know? This is the new vsix https://github.com/lstocchi/vscode-kubernetes-tools/blob/master/vscode-kubernetes-tools-1.3.2.vsix
Thanks

**Comment by Xan2063** [comment]
Hey @lstocchi,

sorry for the late feedback, I was on vacations and didn't have access to the server producing the logs. Tested your changes now:
Here are my results:

* With Highlighting enabled
  * the loading and scrolling is very nice, I like the experience
  * It seems to take some time until the log file is fully loaded as the scrollbar is still expanding. Some feedback on the loading status might be nice, but I can also figure that out from the timestamps
* With Highlighting disable
  *  this seems to be worse than before, almost unusable

Thanks for the big improvement here

**Comment by lstocchi** [comment]
@Xan2063 no worries and thanks for the feedback. 
Cool, so it works fine with the highlighting now. Need to check why with the highligthing disabled it is slow but i'm also thinking that that option has no reason to exist anymore. I created it as a hack for the slowness issue we had at the beginning but now that the loading process changed we can keep the highlighting always enabled. Or would you like to keep that option available?

**Comment by Xan2063** [comment]
I don't think the other view is necessary, if needed I can always export to a file or the terminal.
