### ISSUE TITLE
issue empty list for secrets child tree'is back

### ISSUE THREAD

**Issue by teamtitangithub** [Azure/vscode-kubernetes-tools#968]
I would reopen https://github.com/Azure/vscode-kubernetes-tools/issues/823, but i don't have the right.
Same symptom since viscode /plugin update
![image](https://user-images.githubusercontent.com/80030984/124672102-c5dde580-deb6-11eb-8167-bf7b6c35a083.png)
![image](https://user-images.githubusercontent.com/80030984/124672134-d3936b00-deb6-11eb-9b0e-ca9744fd737c.png)
![image](https://user-images.githubusercontent.com/80030984/124672164-de4e0000-deb6-11eb-818b-b39efcbf2d82.png)

kubectl get secret  -o wide | wc 
280 secrets found

**Comment by itowlson** [comment]
Looking back at #823 I'm not sure we ever got to the bottom of it - @bacongobbler looks like you were investigating it - any ideas?

**Comment by bacongobbler** [comment]
I wasn't able to reproduce the original issue. Not sure what would cause it, sorry!

**Comment by teamtitangithub** [comment]
well the same as before
Big secrets (binary charts) prodcued by helm

**Comment by lstocchi** [comment]
I was able to replicate it. With many big secrets the execution fails but nothing is shown to the user

```
{code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER', stdout: '{
    "apiVersion": "v1",
    "items": [
    …48987293474568886373506650520017949604682885', stderr: ''}
```

**Comment by bacongobbler** [comment]
Interesting... So is this an upstream bug with `helm list` or the extension?

I know there have been a few issues related to server-side release filtering with `helm list` in Helm 2. The changes in Helm 3 to scope the client to the namespace should have resolved most cases.

This use case doesn't seem like something Helm sees on a regular basis, as we're talking about a VERY large release ledger with VERY large release metadata stored in etcd for a single application. At this scale we've heard people move to alternative storage backends like the [SQL storage backend](https://helm.sh/docs/topics/advanced/#sql-storage-backend), as relational databases tend to handle "big data" with ease when compared against etcd's RAFT protocol. The RAFT protocol is quite sensitive to network and disk IO changes.

In any case, if you can identify a bug in Helm, we'd appreciate a report. At the very least we should see if we can guard against this scenario either through pagination or some other technique.

**Comment by lstocchi** [comment]
@bacongobbler i found the error inside the extension. When it tries to execute the command `get secret -o json` it ends up with that error, but it can also happen with configMaps, for example, if they are too big. This is not a problem only related to secrets generated by helm. Or maybe i found another issue? :thinking: 
BTW I created big secrets without using helm (~1MB size)

**Comment by itowlson** [comment]
> So is this an upstream bug with helm list or the extension

This is when we access secrets directly via kubectl.  It's not using `helm list`.  That the secrets were created via Helm is, as Luca says, incidental.

@lstocchi I bet you are right that it affects configmaps as well, but we are seeing it more with secrets because lots of people use Helm and that creates lots of secrets.  It is almost certainly the same extension code for configmaps and secrets.

Are you able to look at this or are you a bit swamped at the moment *grin*?

**Comment by brendandburns** [comment]
fwiw, my bet is that we're trying to load the entire stdout buffer in one go, rather than taking it as a stream, and that we're running into some sort of max buffer size (judging by the error above)

If you look at this:
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

The default max size is 1Mb, sounds like yours are bigger than that.

**Comment by lstocchi** [comment]
> Are you able to look at this or are you a bit swamped at the moment _grin_?

Yes, finishing one thing and i'll work on it :+1:
