### ISSUE TITLE
Support K3D (k3s)

### ISSUE THREAD

**Issue by arash-bizcover** [Azure/vscode-kubernetes-tools#978]
Support using K3D(k3s) rather than minikube.
https://k3d.io/

**Comment by lstocchi** [comment]
Hi @arash-bizcover, thanks for opening this and sorry for the late response. Can you please clarify a bit more what you would expect from this extension? Never played with k3d before but i guess the k8s extension works with it as well, no? What kind of issues do you have? Or by "support k3d" you mean adding the workflow to create a k3d cluster directly from vscode?

**Comment by arash-bizcover** [comment]
Hi @lstocchi 

It is better than minkube. by supporting it, I meant vscode extension deal with it however it is dealing with minikube at the moment. All operations you can do with minikube to be able to do against k3s.

**Comment by gorkem** [comment]
Have you tried  https://marketplace.visualstudio.com/items?itemName=inercia.vscode-k3d

**Comment by arash-bizcover** [comment]
I have @gorkem. It sucks

**Comment by itowlson** [comment]
Let me provide a bit of background.  (cc @squillace who articulates this philosophy more clearly and more forcefully than I do)

A principle of this extension that has evolved over time is to try to keep it agnostic about specific distributions or implementations of Kubernetes.  I emphasise "over time," because you can rightly point to the integrated Minikube support (and the presence of Azure in the connection wizard) as support for a specific implementation.  Guilty as charged!  But that was grandfathered in from the early days of the extension, when we didn't really have such a clear sense of scope.  If I had my time again, I would _not_ bake Minikube in, but would instead write a Minikube-specific extension that integrated nicely with the main k8s extension and exposed Minikube-specific functionality such as start and stop, etc.

So going forward that's how we're trying to handle things like k3d, Microk8s, etc. - not baking them into the fabric of the extension, but providing hooks for the authors and users of those implementations to integrate them, and to provide the user experiences they - with their specific knowledge of their product and community that we lack - see as important.

You clearly feel that the Inercia k3d plugin doesn't adequately meet k3d users' needs.  Whereas I glanced at their marketplace page, and it looked pretty similar to the sort of thing that I'd likely do if we were integrating this into the core extension.  Which only goes to reinforce my feeling that I for one don't know enough about what k3d users need to design something good for them!

I'd suggest the way forward on this is something like:

* Let's have a conversation in this thread about what you'd like from a k3d integration, and where the gaps are between what you want and what Inercia does.
* Then let's talk to Inercia and see if they're amenable to us opening issues on the k3d extension to close those gaps.
* I'll provide technical support (if desired) to Inercia on integration with the base extension and assist with implementing any base extension touchpoints that Inercia needs and we don't already expose.

The alternative is to start a new k3d plugin.  Again, I'd be very happy to provide integration support, or scaffold the project ready for more knowledgeable folks to dive in, or whatever; but I don't feel qualified to _actually work on a k3d user experience myself._

I'm conscious this isn't the answer you were looking for, but hope it still sounds like a positive way forward!  I'd really love to see good experiences for these more specific Kubernetes implementations so I really hope we can make something happen here.
